In [1]:
import torch
import numpy as np

# TENSORS

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.9254e-14, 4.5863e-41, 1.9254e-14],
        [4.5863e-41, 3.3995e-06, 6.7356e+22],
        [1.6131e-07, 1.3086e-11, 2.1748e+23],
        [1.6878e-07, 2.1251e-07, 4.1961e-08],
        [3.3242e+21, 2.3053e-12, 1.1495e+24]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6472, 0.9311, 0.8053],
        [0.9573, 0.8295, 0.0972],
        [0.0533, 0.1552, 0.7975],
        [0.5078, 0.5052, 0.3295],
        [0.9011, 0.1534, 0.0338]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = torch.ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.6539, 0.5455, 0.5039],
        [0.0174, 0.2762, 0.1647],
        [0.1176, 0.2354, 0.8613],
        [0.3338, 0.2801, 0.9998],
        [0.6973, 0.6398, 0.4875]])


In [8]:
print(x.size())

torch.Size([5, 3])


## Operations

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2416, 0.5599, 0.9801],
        [0.7020, 1.1820, 0.4080],
        [0.1602, 1.0873, 1.6074],
        [0.7217, 0.7616, 1.1646],
        [1.1007, 0.7649, 0.6946]])


In [10]:
print(torch.add(x, y))

tensor([[1.2416, 0.5599, 0.9801],
        [0.7020, 1.1820, 0.4080],
        [0.1602, 1.0873, 1.6074],
        [0.7217, 0.7616, 1.1646],
        [1.1007, 0.7649, 0.6946]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.2416, 0.5599, 0.9801],
        [0.7020, 1.1820, 0.4080],
        [0.1602, 1.0873, 1.6074],
        [0.7217, 0.7616, 1.1646],
        [1.1007, 0.7649, 0.6946]])


In [12]:
# Slicing
print(x[:, 1])

tensor([0.5455, 0.2762, 0.2354, 0.2801, 0.6398])


In [13]:
# Reshaping
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.randn(1)
print(x)
print(x.item()) # To access the only element in a tensor

tensor([0.2779])
0.27793803811073303


# NUMPY BRIDGE

## Converting a Torch Tensor to a Numpy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting Numpy Array to Torch Tensor

In [18]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA TENSORS

In [19]:
x = torch.randn(1)
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([-0.1944], device='cuda:0')
tensor([-0.1944], dtype=torch.float64)
