In [1]:
import torch

In [2]:
torch.__version__

'0.4.1'

In [3]:
i = torch.LongTensor([[0, 2], [1, 0], [1, 2]])
v = torch.FloatTensor([3, 4, 5])

In [4]:
torch.sparse.FloatTensor(i.t(), v, torch.Size([2,3])).to_dense()

tensor([[0., 0., 3.],
        [4., 0., 5.]])

In [5]:
sparse = torch.sparse.FloatTensor(i.t(), v, torch.Size([2,3]))

In [7]:
sparse[0, :].to_dense()

RuntimeError: sparse tensors do not have strides

In [8]:
help(sparse)

Help on Tensor in module torch object:

class Tensor(torch._C._TensorBase)
 |  Method resolution order:
 |      Tensor
 |      torch._C._TensorBase
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__ = abs(...)
 |      abs() -> Tensor
 |      
 |      See :func:`torch.abs`
 |  
 |  __array__(self, dtype=None)
 |      # Numpy array interface, to support `numpy.asarray(tensor) -> ndarray`
 |  
 |  __array_wrap__(self, array)
 |      # Wrap Numpy array again in a suitable tensor when done, to support e.g.
 |      # `numpy.sin(tensor) -> tensor` or `numpy.greater(tensor, 0) -> ByteTensor`
 |  
 |  __deepcopy__(self, memo)
 |  
 |  __dir__(self)
 |      __dir__() -> list
 |      default dir() implementation
 |  
 |  __eq__ = eq(...)
 |      eq(other) -> Tensor
 |      
 |      See :func:`torch.eq`
 |  
 |  __floordiv__(self, other)
 |  
 |  __format__(self, format_spec)
 |      default object formatter
 |  
 |  __ge__ = ge(...)
 |      ge(other) -> Tensor
 |      
 |    

In [9]:
import numpy as np

In [11]:
i = np.array([[0, 2], [1, 0], [1, 2]])
v = np.array([3, 4, 5])

In [12]:
import scipy.sparse

In [17]:
sp = scipy.sparse.csr_matrix((v, (i[:, 0], i[:, 1])), shape=(3,3))

In [19]:
sp.todense()

matrix([[0, 0, 3],
        [4, 0, 5],
        [0, 0, 0]], dtype=int64)

In [20]:
sp

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [22]:
sp[1,:]

<1x3 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [23]:
sp[1,:].todense()

matrix([[4, 0, 5]])

In [24]:
sp[:, 1].todense()

matrix([[0],
        [0],
        [0]])

In [27]:
np.array(sp[:, 1].todense()).flatten()

array([0, 0, 0])

In [29]:
x = np.ones([1, 10])
y = np.ones([1, 10])
z = np.ones([1, 10])

In [30]:
current_list = [x, y, z]

In [31]:
current_list

[array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])]

In [33]:
out = np.concatenate(current_list)

In [34]:
print(out)
print(out.shape)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
(3, 10)


# 1-D sparse tensor

In [38]:
i = torch.LongTensor([[0, 5, 9]])
v = torch.FloatTensor([3, 4, 5])

In [39]:
sparse = torch.sparse.FloatTensor(i, v, torch.Size([10]))

In [40]:
sparse

torch.sparse.FloatTensor of size (10,) with indices:
tensor([[0, 5, 9]])
and values:
tensor([3., 4., 5.])

In [45]:
help(sparse.toDense())

AttributeError: 'Tensor' object has no attribute 'toDense'

In [43]:
print(torch.__version__)

0.4.1
